name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"
        architecture: x64
    - run: sudo apt-get update
    - run: sudo apt-get install -y libgirepository1.0-dev
    - uses: actions/checkout@v2
    - run: pip3 install poetry
    - run: ./ci.sh
